world:
    handler: lambda/world/handler.main
    description: World lambda
    memorySize: 2048
    timeout: 30
    role: LambdaExecutionRole
    events:
        - http:
              path: /world
              method: POST
              authorizer:
                  type: request
                  name: authorizer
                  identitySource: method.request.header.Authorization
                  resultTtlInSeconds: 600
              request:
                  schemas:
                      application/json:
                          schema: ${file(./lambda/world/schema.json)}
    environment:
        SAMPLE_TEMPLATE_TABLE_NAME: 'sample-template-table'
