Resources:
    SampleTemplateTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
            TableName: 'sample-template-table'
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
                - AttributeName: type
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
                - AttributeName: type
                  KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
